name: CI/CD to Azure Container Registry

env:
  AZURE_CONTAINER_REGISTRY: petregistry.azurecr.io
  AZURE_CONTAINER_REGISTRY_USERNAME: petregistry
  PET_STORE_APP_IMAGE_NAME: petstoreapp
  PET_STORE_ORDER_SERVICE_IMAGE_NAME: petstoreorderservice
  PET_STORE_PET_SERVICE_IMAGE_NAME: petstorepetservice
  PET_STORE_PRODUCT_SERVICE_IMAGE_NAME: petstoreproductservice

on: [push]

jobs:
  build-pet-store-app:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Maven build
        run: |
          mvn -f ./petstore/petstoreapp --batch-mode --update-snapshots verify

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./petstore/petstoreapp/target/${{ env.PET_STORE_APP_IMAGE_NAME }}-0.0.1-SNAPSHOT.jar

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.WEBAPPSECRET }}

      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build ./petstore/petstoreapp -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_APP_IMAGE_NAME }}:latest -t ${{env.AZURE_CONTAINER_REGISTRY}}/${{ env.PET_STORE_APP_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_APP_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_APP_IMAGE_NAME }}:latest
  build-pet-store-order-service:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Maven build
        run: |
          mvn -f ./petstore/petstoreorderservice --batch-mode --update-snapshots verify

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./petstore/petstoreorderservice/target/${{ env.PET_STORE_ORDER_SERVICE_IMAGE_NAME }}-0.0.1-SNAPSHOT.jar

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.WEBAPPSECRET }}

      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build ./petstore/petstoreorderservice -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_ORDER_SERVICE_IMAGE_NAME }}:latest -t ${{env.AZURE_CONTAINER_REGISTRY}}/${{ env.PET_STORE_ORDER_SERVICE_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_ORDER_SERVICE_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_ORDER_SERVICE_IMAGE_NAME }}:latest
  build-pet-store-pet-service:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Maven build
        run: |
          mvn -f ./petstore/petstorepetservice --batch-mode --update-snapshots verify

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./petstore/petstorepetservice/target/${{ env.PET_STORE_PET_SERVICE_IMAGE_NAME }}-0.0.1-SNAPSHOT.jar

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.WEBAPPSECRET }}

      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build ./petstore/petstorepetservice -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_PET_SERVICE_IMAGE_NAME }}:latest -t ${{env.AZURE_CONTAINER_REGISTRY}}/${{ env.PET_STORE_PET_SERVICE_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_PET_SERVICE_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_PET_SERVICE_IMAGE_NAME }}:latest
  build-pet-store-product-service:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Maven build
        run: |
          mvn -f ./petstore/petstoreproductservice --batch-mode --update-snapshots verify

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./petstore/petstoreproductservice/target/${{ env.PET_STORE_PRODUCT_SERVICE_IMAGE_NAME }}-0.0.1-SNAPSHOT.jar

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.WEBAPPSECRET }}

      - name: Build and push Docker image to Azure Container Registry
        run: |
          docker build ./petstore/petstoreproductservice -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_PRODUCT_SERVICE_IMAGE_NAME }}:latest -t ${{env.AZURE_CONTAINER_REGISTRY}}/${{ env.PET_STORE_PRODUCT_SERVICE_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_PRODUCT_SERVICE_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PET_STORE_PRODUCT_SERVICE_IMAGE_NAME }}:latest
